package com.example.eray_roge

const val MAX_NO_OF_WORDS = 10
const val SCORE_INCREASE = 20
const val WRONG_WORD_SCORE_DECREASE = 10

val allWords = setOf(
    "arooryo",
    "aar",
    "axdi",
    "baaritaan",
    "bocool",
    "beexaan",
    "beexaan",
    "caabbi",
    "cibaar",
    "cowro",
    "dilaaye",
    "duufaan",
    "dhowrasho",
    "eegmo",
    "eed",
    "filasho",
    "faalo",
    "fariid",
    "gumaad",
    "gogol",
    "gaabsi",
    "hubaal",
    "hoorin",
    "haraadi",
    "inkiraad",
    "iimaan",
    "inkaar",
    "jaar",
    "joogso",
    "jalaato",
    "kaalmo",
    "korin",
    "kuleel",
    "laami",
    "leer",
    "liin",
    "maanso",
    "muraad",
    "mooro",
    "nabsi",
    "naceyb",
    "nirig",
    "oon",
    "oomo",
    "olol",
    "qaraami",
    "quursi",
    "qoor",
    "raagid",
    "roob",
    "run",
    "subac",
    "silac",
    "sonkor",
    "tumaal",
    "taako",
    "tuur",
    "uunsi",
    "umul",
    "uur",
    "walwal",
    "weerar",
    "xumaan",
    "xaal",
    "xigasho",
    "yool",
    "yaanyuur",
    "yadadiilo",
)